OD-535[ADD] added Logout option for link component
Fliplet/fliplet-widget-link pull request #53
Opened 2021-09-01 13:37 UTC by OleksandrLavrynenko

@sofiiakvasnevska @inna-bieshulia

OD-535https://weboo.atlassian.net/browse/OD-535

## Description
The "Log Out" option has been added to the "Link" component. It allows user to setup options for the "Log Out" components such as Button, Inline text link, Menu and List (no thumbnail)

## Screenshots/screencasts
https://storyxpress.co/video/kt1hvxxdlj0ten883

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2021-09-03 10:33 UTC, tonytlwu requested changes

2021-09-03 10:33 UTC, tonytlwu commented on js/interface.js
> +function onChange() {
```suggestion
function onActionChange() {
```

2021-09-03 11:24 UTC, OleksandrLavrynenko commented on js/interface.js
> +function onChange() {
I fixed this

2021-09-03 16:54 UTC, tonytlwu approved these changes
@sofiiakvasnevska @inna-bieshulia This is ready for testing

Risk: High
Affected: All components features that support configuring links
Verify: Link actions are correctly displayed, loaded and saved

Squash and merge: Use PR title

2021-09-06 09:52 UTC, merged

2021-09-14 11:09 UTC, squallstar commented on interface.html
> +              <option value="logout">Log Out</option>
This should be "Log out", not "Log Out".

2021-09-14 11:11 UTC, squallstar commented on interface.html
> +              <option value="logout">Log Out</option>
@tonytlwu cc ^